version: '3'

networks:
  serviciosmongo_mynetwork:
    external: true

services:
  nfs1-server:
    image: gists/nfs-server  # Cambiado a una imagen que funciona
    container_name: nfs1-server
    privileged: true
    # ports:
    #   - "2049:2049"
    cap_add:
      - SYS_ADMIN
      - SETPCAP
    environment:
      - "NFS_DOMAIN=*"
      - "NFS_OPTION=fsid=0,rw,sync,insecure,all_squash,anonuid=65534,anongid=65534,no_subtree_check,nohide"
    volumes:
      - ./shared_1:/nfs-share
    networks:
      serviciosmongo_mynetwork:
        ipv4_address: 192.168.1.12

  nfs2-server:
    image: gists/nfs-server
    container_name: nfs2-server
    privileged: true
    # ports:
    #   - "2049:2049"
    cap_add:
      - SYS_ADMIN
      - SETPCAP
    environment:
      - "NFS_DOMAIN=*"
      - "NFS_OPTION=fsid=0,rw,sync,insecure,all_squash,anonuid=65534,anongid=65534,no_subtree_check,nohide"
    volumes:
      - ./shared_2:/nfs-share
    networks:
      serviciosmongo_mynetwork:
        ipv4_address: 192.168.1.13

  nfs3-server:
    image: gists/nfs-server
    container_name: nfs3-server
    privileged: true
    # ports:
    #   - "2049:2049"
    cap_add:
      - SYS_ADMIN
      - SETPCAP
    environment:
      - "NFS_DOMAIN=*"
      - "NFS_OPTION=fsid=0,rw,sync,insecure,all_squash,anonuid=65534,anongid=65534,no_subtree_check,nohide"
    volumes:
      - ./shared_3:/nfs-share:rw
    networks:
      serviciosmongo_mynetwork:
        ipv4_address: 192.168.1.14
