version: '3'

networks:
  mynetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "192.168.1.0/24"

services:
  cfgsvr1:
    container_name: cfgsvr1
    image: mongo
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db
    networks:
      mynetwork:
        ipv4_address: 192.168.1.2
    expose:
      - "27017"
    volumes:
      - cfgsvr1:/data/db

  cfgsvr2:
    container_name: cfgsvr2
    image: mongo
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db
    networks:
      mynetwork:
        ipv4_address: 192.168.1.3
    expose:
      - "27017"
    volumes:
      - cfgsvr2:/data/db

  cfgsvr3:
    container_name: cfgsvr3
    image: mongo
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db
    networks:
      mynetwork:
        ipv4_address: 192.168.1.4
    expose:
      - "27017"
    volumes:
      - cfgsvr3:/data/db

  shard1svr1:
    container_name: shard1svr1
    image: mongo
    command: mongod --shardsvr --replSet shard1rs --port 27017 --dbpath /data/db
    networks:
      mynetwork:
        ipv4_address: 192.168.1.5
    expose:
      - "27017"
    volumes:
      - shard1svr1:/data/db

  shard1svr2:
    container_name: shard1svr2
    image: mongo
    command: mongod --shardsvr --replSet shard1rs --port 27017 --dbpath /data/db
    networks:
      mynetwork:
        ipv4_address: 192.168.1.6
    expose:
      - "27017"
    volumes:
      - shard1svr2:/data/db

  shard1svr3:
    container_name: shard1svr3
    image: mongo
    command: mongod --shardsvr --replSet shard1rs --port 27017 --dbpath /data/db
    networks:
      mynetwork:
        ipv4_address: 192.168.1.7
    expose:
      - "27017"
    volumes:
      - shard1svr3:/data/db

  shard2svr1:
    container_name: shard2svr1
    image: mongo
    command: mongod --shardsvr --replSet shard2rs --port 27017 --dbpath /data/db
    networks:
      mynetwork:
        ipv4_address: 192.168.1.8
    expose:
      - "27017"
    volumes:
      - shard2svr1:/data/db

  shard2svr2:
    container_name: shard2svr2
    image: mongo
    command: mongod --shardsvr --replSet shard2rs --port 27017 --dbpath /data/db
    networks:
      mynetwork:
        ipv4_address: 192.168.1.9
    expose:
      - "27017"
    volumes:
      - shard2svr2:/data/db

  shard2svr3:
    container_name: shard2svr3
    image: mongo
    command: mongod --shardsvr --replSet shard2rs --port 27017 --dbpath /data/db
    networks:
      mynetwork:
        ipv4_address: 192.168.1.10
    expose:
      - "27017"
    volumes:
      - shard2svr3:/data/db
      
container_name: mongos
    image: mongo
    command: mongos --configdb cfgrs/192.168.1.2:27017,192.168.1.3:27017,192.168.1.4:27017 --bind_ip 0.0.0.0 --port 27017
    networks:
      mynetwork:
        ipv4_address: 192.168.1.11
    expose:
      - "27017"


  

volumes:
  cfgsvr1: {}
  cfgsvr2: {}
  cfgsvr3: {}
  shard1svr1: {}
  shard1svr2: {}
  shard1svr3: {}
  shard2svr1: {}
  shard2svr2: {}
  shard2svr3: {}
